### PR TITLE
Date implementation

### LINKED ISSUE #103: [PE-D] [Exception Handling] Lack of exception for invalid date
Add function accepts inputs for invalid data  e.g. 2022-02-35 

Also date formats not specified

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: timchang27/ped#2

### PR DESCRIPTION
**Pull request by shunyao643**
Have implemented Date, please let me know if there is any test cases or bits where I've missed out, thanks!

Changelog:
1. Switched the entire codebase to use Java's `LocalDate` API for date fields
2. Refactor `ModificationCommand#prepareModification` to perform type conversions inside set... classes

closes #103

### CODE REVIEW

File: src/main/java/seedu/command/ModificationCommand.java [hunk 1]
```diff
@@ -15,10 +17,12 @@
     public static final String INVALID_TYPE_MESSAGE = "Equipment Type needs to be one of:" + System.lineSeparator()
             + EquipmentType.getAllTypes();
     public static final String INVALID_COST_MESSAGE = "Cost needs to be able to be parsed to a double";
+    public static final String INVALID_DATE_MESSAGE = "Date needs to be able to be parsed, make sure you're using "
```
Comment (yuhaochua) [inline src/main/java/seedu/command/ModificationCommand.java:20]: I think we could refactor this static String into Command instead? Since other commands might also use it such as CheckCommand

**Review by yuhaochua — COMMENTED** [review]
Looks good generally! But do we also need test cases for wrong date formats in the other classes such as CheckCommand, rather than just for ModificationCommand?

**Review by Bryan-BC — APPROVED** [review]
LGTM for the equipment manager part not 100% sure about the commands but it looks good.

File: src/main/java/seedu/command/ModificationCommand.java (hunk 1 above)
Comment (yuhaochua) [reply src/main/java/seedu/command/ModificationCommand.java:20]: Oh and, I think maybe we need to change CheckCommand as well? Because there is Pair being used there as well and the date is being passed to EquipmentManager through CheckCommand also

Comment (shunyao643) [reply src/main/java/seedu/command/ModificationCommand.java:20]: > I think we could refactor this static String into Command instead? Since other commands might also use it such as CheckCommand

Sure, sounds good

Comment (shunyao643) [reply src/main/java/seedu/command/ModificationCommand.java:20]: Perhaps all the invalid messages can be moved to Command?
