### PR TITLE
Loosen restrictions for modification command regex

### LINKED ISSUE #132: Wrong error message when wrong tags are used for update command
Prerequisites: run ``add n/`SpeakerB` s/`S1404115ASF` t/`Speaker` c/`1000` pf/`Loud_Technologies` pd/`2022-02-23` ``

image

Test input: ``update s/`S1404115ASF` rand/`SpeakerC` c/`2510` pd/`2022-08-21` ``
When executing update command, providing a wrong tag after the serial number seems to give a wrong error message. 

image

Test input: ``update s/`S1404115ASF` c/`2510` rand/`SpeakerC` pd/`2022-08-21` ``
When the wrong tag is placed after another tag, the update goes through without any error and ignores whatever tag was before the wrong tag.

image

Test input: ``update s/`S1404115ASF` name/`SpeakerC` c/`2510` pd/`2022-08-21` ``
Strangely enough, if `name`  tag is used instead of `rand` tag after serial number, the update goes through.

### PR DESCRIPTION
**Pull request by shunyao643**
Removed requirement of matching next regex and added test case to demonstrate the ideal behaviour.

closes #132

### CODE REVIEW

File: src/main/java/seedu/parser/Parser.java [hunk 1]
```diff
@@ -62,24 +59,22 @@
...
-
     public static final Pattern CHECK_COMMAND_FORMAT = Pattern.compile("^(?<itemName>" + ARGUMENT_PAIR_REGEX + ")$");
     public static final Pattern DELETE_COMMAND_FORMAT = Pattern.compile("^(?<serialNumber>" + "[Ss]"
             + "\\/" // argument delimiter
             + "`+" //  backticks to enclose string
             + "[\\w\\s\\-\\.]+" // actual argument value
             + "`+" //  backticks to enclose string
             + ")$");
-    public static final String INCORRECT_COMMAND_FORMAT = "Command word not recognised. " + System.lineSeparator()
+    public static final String UNRECOGNISED_COMMAND_MESSAGE = "Command word not recognised. " + System.lineSeparator()
```
Comment (Bryan-BC) [inline src/main/java/seedu/parser/Parser.java:71]: Nice addition with the MESSAGE makes it clearer

**Review by Bryan-BC — APPROVED** [review]

**Review by yuhaochua — APPROVED** [review]
LGTM! Good that you removed the deprecated portions of code.
